<?php

/*
 * Package-Name: Kopete
 * Package-Description: The Default Kopete smilies.
 * Package-Author: Matt Read
 * Package-Author-URI: http://mattread.com/
 */

$wp_smilies = array(

	':-['	=> 'bat.png',
	':['	=> 'bat.png',
	'(B)'	=> 'beer.png',
	'(b)'	=> 'beer.png',
	'(^)'	=> 'cake.png',
	'(P)'	=> 'camera.png',
	'(p)'	=> 'camera.png',
	'(@)'	=> 'cat.png',
	'(O)'	=> 'clock.png',
	'(o)'	=> 'clock.png',
	'(D)'	=> 'cocktail.png',
	'(d)'	=> 'cocktail.png',
	':-S'	=> 'confused.png',
	':S'	=> 'confused.png',
	':-s'	=> 'confused.png',
	':s'	=> 'confused.png',
	':\'('	=> 'cry.png',
	':\'-('	=> 'cry.png',
	';-('	=> 'cry.png',
	';('	=> 'cry.png',
	'(C)'	=> 'cup.png',
	'(c)'	=> 'cup.png',
	'(&amp;)'	=> 'dog.png',
	':-$'	=> 'embarassed.png',
	':$'	=> 'embarassed.png',
	'(E)'	=> 'email.png',
	'(e)'	=> 'email.png',
	'(~)'	=> 'film.png',
	'(K)'	=> 'kiss.png',
	'(k)'	=> 'kiss.png',
	':-X'	=> 'kiss.png',
	':X'	=> 'kiss.png',
	':-x'	=> 'kiss.png',
	':x'	=> 'kiss.png',
	'(I)'	=> 'lightbulb.png',
	'(i)'	=> 'lightbulb.png',
	'(L)'	=> 'love.png',
	'(l)'	=> 'love.png',
	'(8)'	=> 'note.png',
	':-O'	=> 'omg.png',
	':O'	=> 'omg.png',
	':-o'	=> 'omg.png',
	':o'	=> 'omg.png',
	'(T)'	=> 'phone.png',
	'(t)'	=> 'phone.png',
	'(G)'	=> 'present.png',
	'(g)'	=> 'present.png',
	'(F)'	=> 'rose.png',
	'(f)'	=> 'rose.png',
	':-('	=> 'sad.png',
	':('	=> 'sad.png',
	'(H)'	=> 'shade.png',
	'8-)'	=> 'shade.png',
	'8)'	=> 'shade.png',
	':-)'	=> 'smile.png',
	':)'	=> 'smile.png',
	':o)'	=> 'smile.png',
	'(*)'	=> 'star.png',
	':-D'	=> 'teeth.png',
	':D'	=> 'teeth.png',
	':-d'	=> 'teeth.png',
	':d'	=> 'teeth.png',
	'(N)'	=> 'thumbs_down.png',
	'(n)'	=> 'thumbs_down.png',
	'(Y)'	=> 'thumbs_up.png',
	'(y)'	=> 'thumbs_up.png',
	':-P'	=> 'tongue.png',
	':P'	=> 'tongue.png',
	':-p'	=> 'tongue.png',
	':p'	=> 'tongue.png',
	'(U)'	=> 'unlove.png',
	'(u)'	=> 'unlove.png',
	'(W)'	=> 'wilted_rose.png',
	'(w)'	=> 'wilted_rose.png',
	';-)'	=> 'wink.png',
	';)'	=> 'wink.png'

	);


?>